### ISSUE TITLE
ApplicationInstance Boot Errors are being swallowed

### ISSUE THREAD

**Issue by arjansingh** [ember-fastboot/fastboot#76] opened 2016-08-05 23:52 UTC
I ran into a particularly vicious error, where a stray `window` reference caused the `ApplicationInstance` to fail booting:

```
  _bootPromise:
   Promise {
     _id: 14,
     _label: undefined,
     _state: 2,
     _result: [TypeError: window.addEventListener is not a function],
     _subscribers: [],
     _onError: null } }
```

The failure was silent and I only detected it when I logged `this.instance` inside of [`src/result.js`](https://github.com/ember-fastboot/fastboot/blob/master/src/result.js#L56-L67).

We should be logging these events (not swallowing them silently). 

Of course, I'll open a PR but I want to know if `result._finalize` is the place to do the error handling. Suggestions welcome.

**Comment by arjansingh** [comment] 2016-08-11 05:27
Good news (and bad news)! It's not the fastboot middleware. I am able to get this repo to error out locally using `ember-cli-fastboot`. 

I did some preliminary digging and it looks like the boot errors are localized to the instance of [fastboot-app-server](https://github.com/ember-fastboot/fastboot-app-server) that I'm using.

I'll keep digging in that repo to see if I can reach some actual lines of code.

**Comment by arjansingh** [comment] 2016-08-18 02:25
@danmcclain @tomdale 

### Resilient mode is the cause
I was poking around today and found the ultimate source of this issue's problems.

If you have [resilient mode turned on](https://github.com/ember-fastboot/fastboot/blob/master/src/index.js#L70-L77) we just swallow the error instead of throwing it. 

`fastboot-app-sever` has [resilient mode on](https://github.com/ember-fastboot/fastboot-app-server/blob/500c29af6f08715a7b637a378d079c1b8cab744e/src/worker.js#L59-L62).

### Potential solutions
1. Modify the error handling in this project.
2. Modify the error handling in `fastboot-app-server` and add documentation to warn about resilient mode, specifically about how end-users are responsible for manually handling result errors if it is enabled.

Thoughts?

**Comment by tomdale** [comment] 2016-08-18 20:07
This seems like it's working as intended? FastBoot App Server is designed for production, where you typically want to proceed with client-side rendering if server-side rendering fails. It should be caught in development, where `resilient` should be turned off.

Maybe we should add a note recommending running a staging/dev environment with it off?

**Comment by arjansingh** [comment] 2016-08-18 20:33
We still want logging for these errors `fastboot-app-server` because they can still happen in production. Someone could download some bad Ember application code (e.g, a stray `window` reference) on their server and break FastBoot rendering.  

After thinking it over, I think the ideal solution is to have the [`success` function](https://github.com/ember-fastboot/fastboot-express-middleware/blob/master/src/index.js#L35-L52) in `fastboot-express-middleware` check for `result.error` and then log the error if there is one. Because the response is resilient, you never get to the `catch` block.

**Comment by arjansingh** [comment] 2016-08-23 02:20
Ok I was thinking about this more.  I think the proper (and simpler) solution is to make resilient mode configurable in `fastboot-app-server`. I will PR accordingly.

**Comment by danmcclain** [comment] 2016-12-12 02:05
@arjansingh is this still an issue?

**Comment by briangonzalez** [comment] 2017-01-16 21:16
@arjansingh Did you ever PR into `fastboot-app-server` with a configurable resilient mode?

**Comment by briangonzalez** [comment] 2017-01-16 21:58
To add to the noise here: another form of silent error is Fastboot not replacing inserting fastbooted content because it cannot find the injection comments.

https://github.com/ember-fastboot/fastboot/blob/master/src/result.js#L116-L122

We should probably log a warning of some sort if we don't find the injection comments.

This bit us when using fastboot in conjunction with `ember-cli-html-minifier`.

@kratiahuja @danmcclain @arjansingh

**Comment by kratiahuja** [comment] 2017-01-17 03:20
@briangozalez: mind opening a new issue in this repo describing your previous comment?

Of course you are also welcome to send a PR to fix the issue as well :)

**Comment by xg-wang** [comment] 2021-02-09 21:54
The fix PR was already merged into middleware (and consumed by fastboot-app-server).

**Closed by xg-wang** 2021-02-09 21:54 UTC
